\title{
1. Chemical Reactions and Equations
}

\section*{Multiple Choice Questions (MCQs)}

DIRECTIONS : This section contains multiple choice questions. Each question has four choices (a), (b), (c) and (d) out of which ONLY ONE is correct.

1. Which of the following is a decomposition reaction?
(a) $2 \mathrm{HgO} \xrightarrow{\text { Heat }} 2 \mathrm{Hg}+\mathrm{O}_{2}$
(b) $\mathrm{CaCO}_{3} \xrightarrow{\text { Heat }} \mathrm{CaO}+\mathrm{CO}_{2}$
(c) $2 \mathrm{H}_{2} \mathrm{O} \xrightarrow{\text { Electrolysis }} \mathrm{H}_{2}+\mathrm{O}_{2}$
(d) All of these

2. On the basis of following features, identify the correct option.
(i) This reaction occurs during corrosion.
(ii) This reaction occurs during respiration.
(a) Decomposition reaction
(b) Redox reaction
(c) Combination reaction
(d) Endothermic reaction

3. Which of the following is not a physical change?
(a) Boiling of water to give water vapour.
(b) Melting of ice to give water.
(c) Dissolution of salt in water.
(d) Combustion of Liquefied Petroleum Gas (LPG).

4. Which of the following can be decomposed by the action of light?
(a) NaCl
(b) KCl
(c) AgCl
(d) CuCl

5. In which of the following the identity of initial substance remains unchanged?
(a) Curdling of milk
(b) Formation of crystals by process of crystallisation
(c) Fermentation of grapes
(d) Digestion of food

\section*{Assertion \& Reason}

DIRECTIONS : Each of these questions contains an assertion followed by reason. Read them carefully and answer the question on the basis of following options. You have to select the one that best describes the two statements.

(a) If both Assertion and Reason are correct and Reason is the correct explanation of Assertion.

(b) If both Assertion and Reason are correct, but Reason is not the correct explanation of Assertion.

(c) If Assertion is correct but Reason is incorrect.

(d) If Assertion is incorrect but Reason is correct.

1. Assertion : Chlorine gas react with potassium iodide solution to form potassium chloride and iodine.
Reason : Chlorine is more reactive than iodine therefore displaces iodine from potassium iodide.

2. Assertion : When copper strip is placed in ferrous sulphate solution, colour of the solution changes.
Reason : Iron is more reactive than copper.

3. Assertion : Decomposition of vegetable matter into compost is an endothermic reaction.
Reason : Heat is required in an endothermic reaction.

4. Assertion : Reaction of sodium sulphate with barium chloride is a precipitation reaction.
Reason : Precipitation reaction produces insoluble salt.

5. Assertion: When a mixture of hydrogen and chlorine is placed in sunlight, hydrogen chloride is formed.
Reason : It is an example of combination reaction.

\section*{Fill in the Blanks}

\section*{True / False}

\section*{Match the Following}

DIRECTIONS : Each question contains two columns, column I have to be matched with column II.

1. Column II gives type of reaction mention in column I, match them correctly.

Column I

(A) $\mathrm{C}+\mathrm{O}_{2} \rightarrow \mathrm{CO}_{2}$

(B) $\mathrm{AgBr} \xrightarrow{\text { light }} \mathrm{Ag}+\mathrm{Br}$

(C) $\mathrm{Zn}+\mathrm{CuSO}_{4} \rightarrow \mathrm{ZnSO}_{4}+\mathrm{Cu}$

(D) $\mathrm{CH}_{3} \mathrm{CH}_{2} \mathrm{OH} \xrightarrow[\mathrm{CH}_{3} \mathrm{CHO}+\mathrm{H}_{2}]{\mathrm{Cu}}$

\section*{Passage Based Questions}

DIRECTIONS : Study the given paragraph ( $s$ ) and answer the following questions.

\section*{Passage}

Two metals X and Y form the salt $\mathrm{XSO}_{4}$ and $\mathrm{Y}_{2} \mathrm{SO}_{4}$ respectively. The solution of salt $\mathrm{XSO}_{4}$ is blue in colour whereas that of $\mathrm{Y}_{2} \mathrm{SO}_{4}$ is colourless. When barium chloride solution is added to $\mathrm{XSO}_{4}$ solution, then a white precipitate Z is formed alongwith a salt which turns the solution green. And when barium chloride solution is added to $\mathrm{Y}_{2} \mathrm{SO}_{4}$ solution, then the same white precipitate Z is formed alongwith colourless common salt solution.
1. What could the metals X and Y be?
2. Write the name and formula of salt $\mathrm{XSO}_{4}$.
3. Write the name and formula of salt $\mathrm{Y}_{2} \mathrm{SO}_{4}$.
4. What is the name and formula of white precipitate Z?
5. Write the name and formula of the salt which turns the solution green in the first case.

\section*{Very Short Answer Questions}

1. Write a balanced chemical equation when magnesium metal reacts with aqueous hydrochloric acid to produce a solution of magnesium chloride and hydrogen gas.

2. Can a combination reaction be redox reaction?

3. What are the different types of reactions ?

4. What is a decomposition reaction ? Give example.

5. Define displacement reaction.

6. What happens when sodium reacts with water ?

7. Write the chemical equation and name the reaction when a solution of sodium chloride is mixed with a solution of silver nitrate and a white precipitate of silver chloride is formed.

8. Potassium chlorate $\left(\mathrm{KClO}_{3}\right)$ on heating forms potassium chloride and oxygen. Write a balanced equation for this reaction.

9. Give an example of a chemical reaction characterised by the change in temperature.

10. To balance a chemical equation, can we change the formulae of either reactants or products ?

11. Nickel(II) nitrate is prepared by heating nickel metal with liquid dinitrogen tetraoxide. In addition to the nitrate, gaseous nitrogen monoxide is formed. Write the balanced equation.

12. Write a balanced chemical equation with state symbols for the following reactions.
(a) Aquaeous solutions of barium chloride and sodium sulphate react to give insoluble barium sulphate and the solution of sodium chloride.
(b) Sodium hydroxide solution (in water) reacts with hydrochloric acid solution (in water) to produce sodium chloride solution and water.

\section*{Short Answer Questions}

1. In the refining of silver, the recovery of silver from silver nitrate solution involved displacement by copper metal. Write down the reaction involved.

2. Translate the following statements into chemical equations and then balance them.
(a) Hydrogen gas combines with nitrogen to form ammonia.
(b) Hydrogen sulphide gas burns in air to give water and sulphur dioxide
(c) Barium chloride reacts with aluminum sulphate to give aluminum chloride and a precipitate of barium sulphate.
(d) Potassium metal reacts with water to give potassium hydroxide and hydrogen gas.

3. What is rancidity ?

4. Balance the following chemical reactions.
(a) $\mathrm{NH}_{4} \mathrm{NO}_{3} \longrightarrow \mathrm{~N}_{2} \mathrm{O}+\mathrm{H}_{2} \mathrm{O}$
(b) $\mathrm{P}_{4} \mathrm{O}_{10}+\mathrm{H}_{2} \mathrm{O} \longrightarrow \mathrm{H}_{3} \mathrm{PO}_{4}$
(c) $\mathrm{HIO}_{3} \longrightarrow \mathrm{I}_{2} \mathrm{O}_{5}+\mathrm{H}_{2} \mathrm{O}$
(d) $\mathrm{As}+\mathrm{Cl}_{2} \longrightarrow \mathrm{AsCl}_{5}$

5. Balance the chemical equations for the following important industrial processes :
(a) Molecular nitrogen and hydrogen combine to give ammonia.
(b) Molecular hydrogen and carbon monoxide react to form methanol $\left(\mathrm{CH}_{3} \mathrm{OH}\right)$.
(c) $\mathrm{CaO}+\mathrm{C} \longrightarrow \mathrm{CO}+\mathrm{CaC}_{2}$
(d) $\mathrm{C}_{2} \mathrm{H}_{4}+\mathrm{O}_{2}+\mathrm{HCl} \longrightarrow \mathrm{C}_{2} \mathrm{H}_{4} \mathrm{Cl}_{2}+\mathrm{H}_{2} \mathrm{O}$

6. Represent each of the following word reaction with a balanced chemical equation.
(a) Disilane gas $\left(\mathrm{Si}_{2} \mathrm{H}_{6}\right)$ undergoes combustion to form solid silicon dioxide and water.
(b) Solid aluminium hydride is formed by a combination reaction of its two elements.
(c) When solid calcium bisulfite is heated, it decomposes to solid calcium oxide, sulfur dioxide gas, and water.

7. A large piece of zinc metal is placed in a copper (II) sulfate, $\mathrm{CuSO}_{4}$, solution. The blue solution become colourless as copper metal falls to the bottom of the container. The resulting solution contains zinc sulfate, $\mathrm{ZnSO}_{4}$. Write balanced chemical equation for the reaction.

8. A solution of $\mathrm{AgNO}_{3}$ is mixed with a solution of $\mathrm{K}_{2} \mathrm{~S}$. Write the molecular, total ionic and net ionic equations illustrating the reaction.

9. Write decomposition reactions for the following compounds.
(a) $\quad \mathrm{Ca}\left(\mathrm{HCO}_{3}\right)_{2}$
(b) $\quad \mathrm{Ag}_{2} \mathrm{O}$
(c) $\mathrm{N}_{2} \mathrm{O}_{3}$

10. Show that oxidation and reduction reactions go side by side by taking a suitable example.

11. Explain the following in terms of gain or loss of oxygen with two examples each.
(a) Oxidation
(b) Reduction

12. Can oxidation or reduction take place alone? Why or why not? What are such reactions called?

13. (a) Solution of a substance ' X ' is used for testing carbon dioxide. Write the equation of the reaction of ' X ' with carbon dioxide.
(b) How is ' X ' obtained? Write chemical equation.

14. When hydrogen gas is passed over heated copper (II) oxide, copper and steam are formed. Write the balanced chemical equation with physical states for this reaction. State what kind of chemical reaction is this?

15. What is observed when carbon dioxide gas is passed through lime water.
(a) For a short duration?
(b) For a long duration? Also write the chemical equations for the reaction involved.

16. A student added few pieces of aluminium metal to two test tubes A and B containing aqueous solutions of iron sulphate and copper sulphate. In the second part of her experiment, she added iron metal to another test tubes C and D containing aqueous solution of aluminium sulphate and copper sulphate.
In which test tube or test tube will she observe colour change? On the basis of this experiment, state which one is the most reactive metal and why?

17. Identify the type of reactions taking place in each of the following cases and write the balanced chemical equation for the reactions.
(a) Zinc reacts with silver nitrate to produce zinc nitrate and silver.
(b) Potassium iodide reacts with lead nitrate to produce potassium nitrate and lead iodide.

18. 2 g of silver chloride is taken in a china dish and the china dish is placed in sunlight for sometime. What will be your observation in this case? Write the chemical reaction involved in the form of a balanced chemical equation. Identify the type of chemical reaction.

19. Mention with reason the colour changes observed when :
(i) silver chloride is exposed to sunlight.
(ii) copper powder is strongly heated in the presence of oxygen.
(iii) a piece of zinc is dropped in copper sulphate solution.

\section*{Long Answer Questions}

1. What are different types of combination reactions ?

2. A solution of $\mathrm{Na}_{2} \mathrm{CO}_{3}$ is mixed with a solution of $\mathrm{CaCl}_{2}$. Predict what happens.

3. Balance the following equations
(a) $\mathrm{CaCO}_{3} \xrightarrow{\Delta} \mathrm{CaO}+\mathrm{CO}_{2}$
(b) $\mathrm{H}_{2} \mathrm{SO}_{4}+\mathrm{NaOH} \longrightarrow \mathrm{Na}_{2} \mathrm{SO}_{4}+\mathrm{H}_{2} \mathrm{O}$
(c) $\mathrm{H}_{2} \mathrm{O}_{2} \longrightarrow \mathrm{H}_{2} \mathrm{O}+\mathrm{O}_{2}$
(d) $\mathrm{Al}+\mathrm{H}_{3} \mathrm{PO}_{4} \longrightarrow \mathrm{AlPO}_{4}+\mathrm{H}_{2}$
(e) $\quad \mathrm{Ca}(\mathrm{OH})_{2}+\mathrm{HCl} \longrightarrow \mathrm{CaCl}_{2}+\mathrm{H}_{2} \mathrm{O}$

4. Write balanced equations by predicting the products of the following reactions. Include the physical state of each element or compound.
(a) The neutralization of aqueous rubidium hydroxide with hydrobromic acid.
(b) A single-displacement reaction of calcium metal with a nitric acid solution.
(c) The combustion of solid naphthalene $\left(\mathrm{C}_{10} \mathrm{H}_{8}\right)$.
(d) A precipitation reaction involving aqueous ammonium chromate and aqueous barium bromide.
(e) The decomposition of solid aluminum hydroxide into solid aluminum oxide and gaseous water.

5. Identify the type of chemical reaction in the following statements and define each of them :
(a) Digestion of food in our body
(b) Rusting of iron
(c) Heating of manganese dioxide with aluminium powder
(d) Blue colour of copper sulphate solution disappears when iron fillings are added to it
(e) Dilute hydrochloric acid is added to sodium hydroxide solution to form sodium chloride and water.

\section*{Reasoning Based Questions}

1. Why is photosynthesis considered as an endothermic reaction?

2. Why is the amount of gas collected in one of the test tubes in electrolysis of water double of the amount collected in the other? Name this gas.

3. The oxidation of iron to rust is a problem, but the oxidation of aluminium to aluminium oxide is not why?

4. Why the green colour of ferrous sulphate salt changes to brown and produces smell of burning sulphur on strong heating?

5. Why colourless lead nitrate produces a yellow residue and brown fumes on heating?

6. When an aqueous solution of $\mathrm{AgNO}_{3}$ is added to common salt solution, then a white precipitate is formed. Why?

7. Why the formation of black precipitate takes place, when hydrogen sulphide gas is passed through an aqueous solution of $\mathrm{CuSO}_{4}$ ?

8. Why sodium metal reacts violently with water?

9. Why antioxidants are added to fat and oil containing food?

10. Why magnesium ribbon burns in air with a dazzling flame and forms white ash?

\section*{HOTS Questions}

1. A substance X , which is an oxide of a group 2 element, is used intensively in the cement industry. This element is present in bones also. On treatment with water it forms a solution which turns red litmus blue. Identify $X$ and also write the chemical reactions involved.

2. A solution of KBr is mixed with a solution of $\mathrm{Sr}\left(\mathrm{ClO}_{4}\right)_{2}$. Predict what happens.

3. Identify the reducing agent in the following reactions.
(a) $4 \mathrm{NH}_{3}+5 \mathrm{O}_{2} \longrightarrow 4 \mathrm{NO}+6 \mathrm{H}_{2} \mathrm{O}$
(b) $\mathrm{H}_{2} \mathrm{O}+\mathrm{F}_{2} \longrightarrow \mathrm{HF}+\mathrm{HOF}$
(c) $\mathrm{Fe}_{2} \mathrm{O}_{3}+3 \mathrm{CO} \longrightarrow 2 \mathrm{Fe}+3 \mathrm{CO}_{2}$
(d) $2 \mathrm{H}_{2}+\mathrm{O}_{2} \longrightarrow 2 \mathrm{H}_{2} \mathrm{O}$

4. Write balanced equations for the reactions between each of the following oxides and water :
(a) $\mathrm{Li}_{2} \mathrm{O}$
(b) CaO
(c) $\mathrm{SO}_{3}$

5. Represent the following chemical reaction as a balanced equation. Liquid "rubbing alcohol," $\left(\mathrm{C}_{3} \mathrm{H}_{8} \mathrm{O}\right)$ reacts with oxygen to form carbon dioxide gas and water.

6. (a) Would you expect aluminum oxide to be a solid, liquid, or gas at room temperature?
(b) Write the balanced chemical equation for the reaction of aluminum oxide with nitric acid.

7. Consider the following two possible reactions. If a reaction does occur, write the balanced equations illustrating the reactions.
(a) A strip of tin metal is placed in an aqueous $\mathrm{AgNO}_{3}$ solution.
(b) A strip of silver metal is placed in an aqueous perchloric acid solution.

8. Write combination reactions that occur when the metal barium reacts with the following nonmetals.
(a) Hydrogen
(b) Sulfur
(c) Bromine
(d) Nitrogen

\section*{Case Study Based MCQs}

1. Read the following and answer any four questions from (i) to (v).
Chemical reactions involve the breaking and making of bonds between atoms to produce new substances. during a chemical reaction atoms of one element do not change into those of another element. Nor do atoms disappear from the mixture or appear from elsewhere. There are certain types of reactions. Reactions in which a single product is formed from two or more reactants is known as a combination reaction. Decomposition reactions are the reactions in which a compound breaks down into simpler compounds. Displacement and double displacement reactions are the one in which an atom or group of atom is replaced by another.Another type of reaction is redox reactions in which simultaneous oxidation and reduction takes place.
(i) Which of the following reactions involved the combination of two element?
(a) $\mathrm{CaO}+\mathrm{CO}_{2} \rightarrow \mathrm{CaCO}_{2}$
(b) $4 \mathrm{Na}+\mathrm{O}_{2} \rightarrow 2 \mathrm{Na}_{2} \mathrm{O}$
(c) $\mathrm{SO}_{2}+\frac{1}{2} \mathrm{O}_{2} \rightarrow \mathrm{SO}_{3}$
(d) $\mathrm{NH}_{3}+\mathrm{HCl} \rightarrow \mathrm{NH}_{4} \mathrm{Cl}$
(ii) Consider the reaction
$\mathrm{Fe}_{2} \mathrm{O}_{3}+2 \mathrm{Al} \rightarrow \mathrm{Al}_{2} \mathrm{O}_{3}+2 \mathrm{Fe}$
The above reaction is an example of
(a) combination reaction
(b) double displacement reaction
(c) decomposition reaction
(d) simple displacement reaction
(iii) The equation
$\mathrm{Mg}(s)+\mathrm{CuO}(s) \square \rightarrow \mathrm{MgO}(s)+\mathrm{Cu}(s)$ represents
(i) decomposition reaction
(ii) displacement reaction
(iii) combination reaction
(iv) double displacement reaction
(v) redox reaction
(a) (i) and (ii)
(b) (iii) and (iv)
(iv) and (v)
(c) (ii) and (v)
(d)
(iv) Which of the following is a decomposition reaction?
(a) $2 \mathrm{HgO} \xrightarrow{\text { heat }} 2 \mathrm{Hg}+\mathrm{O}_{2}$
(b) $\mathrm{CaCO}_{3} \xrightarrow{\text { heat }} \mathrm{CaO}+\mathrm{CO}_{2}$
(c) $2 \mathrm{H}_{2} \mathrm{O} \xrightarrow{\text { electrolysis }} \mathrm{H}_{2}+\mathrm{O}_{2}$
(d) All of these
(v) $\mathrm{CuO}+\mathrm{H}_{2} \square \rightarrow \mathrm{H}_{2} \mathrm{O}+\mathrm{Cu}$ reaction is an example of -
(a) redox reaction
(b) synthesis reaction
(c) neutralisation
(d) analysis reaction

\section*{Text - Book Questions}

1. Why should a magnesium ribbon be cleaned before burning in air?

2. Write the balanced equation for the following chemical reactions.
(i) Hydrogen + Chlorine ⟶ Hydrogen chloride
(ii) Barium chloride + Aluminium sulphate ⟶ Barium sulphate + Aluminium chloride
(iii) Sodium + Water ⟶
Sodium hydroxide + Hydrogen

3. Write a balanced chemical equation with state symbols for the following reactions.
(i) Solutions of barium chloride and sodium sulphate in water react to give insoluble barium sulphate and the solution of sodium chloride.
(ii) Sodium hydroxide solution (in water) reacts with hydrochloric acid solution (in water) to produce sodium chloride solution and water.

4. A solution of a substance ' X ' is used for white washing.
(i) Name the substance ' X ' and write its formula.
(ii) Write the reaction of the substance ' X ' with water.

5. Why is the amount of gas collected in one of the test tube in activity 1.7 of your NCERT text book double of the amount collected in the other? Name this gas.

6. Why does the colour of copper sulphate solution changes when an iron nail is dipped in it?

7. Give an example of a double displacement reaction other than the one given in activity 1.10 of your NCERT text book.

8. Identify the substances that are oxidised and the substances that are reduced in the following reactions.
(i) $4 \mathrm{Na}(\mathrm{s})+\mathrm{O}_{2}(\mathrm{~g}) \longrightarrow 2 \mathrm{Na}_{2} \mathrm{O}(\mathrm{s})$
(ii) $\mathrm{CuO}(\mathrm{s})+\mathrm{H}_{2}(\mathrm{~g}) \longrightarrow \mathrm{Cu}(\mathrm{s})+\mathrm{H}_{2} \mathrm{O}(\mathrm{l})$

\section*{Text - Book Exercise}

1. Which of the statements about the reaction below are incorrect?
$2 \mathrm{PbO}(\mathrm{s})+\mathrm{C}(\mathrm{s}) \longrightarrow 2 \mathrm{~Pb}(\mathrm{~s})+\mathrm{CO}_{2}(\mathrm{~g})$
(i) Lead is getting reduced.
(ii) Carbon dioxide is getting oxidised.
(iii) Carbon is getting oxidised.
(iv) Lead oxide is getting reduced.
(a) (i) and (ii)
(b) (i), (ii) and (iii)
(c) (i) and (iii)
(d) all

2. $\mathrm{Fe}_{2} \mathrm{O}_{3}+2 \mathrm{Al} \longrightarrow \mathrm{Al}_{2} \mathrm{O}_{3}+2 \mathrm{Fe}$
The above reaction is an example of a :
(a) combination reaction
(b) double displacement reaction
(c) decomposition reaction
(d) displacement reaction.

3. What happens when dilute hydrochloric acid is added to iron fillings? Tick the correct answer.
(a) Hydrogen gas and iron chloride are produced.
(b) Chlorine gas and iron hydroxide are produced.
(c) No reaction takes place.
(d) Iron salt and water are produced.

4. What is a balanced chemical equation? Why should chemical equations be balanced?

5. Translate the following statements into chemical equations and then balance them.
(a) Hydrogen gas combines with nitrogen to form ammonia.
(b) Hydrogen sulphide gas burns in air to give water and sulphur dioxide.
(c) Barium chloride reacts with aluminium sulphate to give aluminium chloride and a precipitate of barium sulphate.
(d) Potassium metal reacts with water to give potssium hydroxide and hydrogen gas.

6. Balance the following chemical equations.
(a) $\mathrm{HNO}_{3}+\mathrm{Ca}(\mathrm{OH})_{2} \longrightarrow \mathrm{Ca}\left(\mathrm{NO}_{3}\right)_{2}+\mathrm{H}_{2} \mathrm{O}$
(b) $\mathrm{NaOH}+\mathrm{H}_{2} \mathrm{SO}_{4} \longrightarrow \mathrm{Na}_{2} \mathrm{SO}_{4}+\mathrm{H}_{2} \mathrm{O}$
(c) $\mathrm{AgNO}_{3}+\mathrm{NaCl} \longrightarrow \mathrm{AgCl}+\mathrm{NaNO}_{3}$.
(d) $\mathrm{BaCl}_{2}+\mathrm{H}_{2} \mathrm{SO}_{4} \longrightarrow \mathrm{BaSO}_{4}+\mathrm{HCl}$

7. Write the balanced chemical equations for the following reactions.
(a) Calcium hydroxide + Carbon dioxide ⟶
Calcium carbonate + water
(b) Zinc + Silver nitrate ⟶ Zinc nitrate + Silver
(c) Aluminium + Copper chloride ⟶
Aluminium chloride + Copper
(d) Barium chloride + Potassium sulphate ⟶
Barium sulphate + Potassium chloride

8. Write the balanced chemical equation for the following and identify the type of reaction in each case.
(a) Potassium bromide(aq) + Barium iodide(aq)
⟶ Potassium iodide(aq) + Barium bromide(s)
(b) Zinc carbonate(s) ⟶
Zinc oxide(s) + Carbon dioxide(s)
(c) Hydrogen(g) + Chlorine (g) ⟶
Hydrogen chloride(g)
(d) Magnesium(s) + Hydrochloric acid(aq)
⟶ Magnesium chloride(aq) + Hydrogen(g)

9. What does one mean by exothermic and endothermic reaction? Give examples.

10. Why is respiration considered an exothermic reaction? Explain.

11. Why are decomposition reactions called the opposite of combination reactions? Write equations for these reactions.

12. What is the difference between displacement and double displacement reactions? Write equations for these reactions.

13. In the refining of silver, the recovery of silver from silver nitrate solution involved displacement by copper metal. Write down the reaction involved.

14. What do you mean by a precipitation reaction? Explain by giving examples.

15. A shiny brown coloured element ' $X$ ' on heating in air becomes black in colour. Name the element ' X ' and the black coloured compound formed.

16. Why do we apply paint on iron articles?

17. Oil and fat containing food items are flushed with nitrogen. Why?

18. Explain the following terms with one example each.
(a) Corrosion
(b) Rancidity

19. Write chemical equation for decomposition reactions where energy is supplied in the form of (i) heat (ii) light (iii) electricity.

\section*{Exemplar Questions}

1. Complete the missing components/variables given as $x$ and $y$ in the following reactions
(i) $\mathrm{Pb}\left(\mathrm{NO}_{3}\right)_{2}(\mathrm{aq})+2 \mathrm{KI}(\mathrm{aq}) \longrightarrow \mathrm{PbI}_{2}(x)+\mathrm{KNO}_{3}(y)$
(ii) $\mathrm{Cu}(\mathrm{s})+2 \mathrm{AgNO}_{3}(\mathrm{aq}) \longrightarrow \mathrm{Cu}\left(\mathrm{NO}_{3}\right)_{2}(\mathrm{aq})+x(s)$
(iii) $\mathrm{Zn}(\mathrm{s})+\mathrm{H}_{2} \mathrm{SO}_{4}(\mathrm{aq}) \longrightarrow \mathrm{ZnSO}_{4}(x)+\mathrm{H}_{2}(y)$
(iv) $\mathrm{CaCO}_{3}(\mathrm{~s}) \xrightarrow{x} \mathrm{CaO}(\mathrm{s})+\mathrm{CO}_{2}(\mathrm{~g})$

2. Grapes hanging on the plant do not ferment but after being plucked from the plant can be fermented. Under what conditions do these grapes ferment? Is it a chemical or a physical change?

3. During the reaction of some metals with dilute hydrochloric acid, following observations were made.
(i) Silver metal does not show any change
(ii) The temperature of the reaction mixture rises when aluminium (Al) is added.
(iii) The reaction of sodium metal is found to be highly explosive.
(iv) Some bubbles of a gas are seen when lead ( Pb ) is reacted with the acid.
Explain these observations giving suitable reasons.

4. Ferrous sulphate decomposes with the evolution of a gas having a characteristic odour of burning sulphur. Write the chemical reaction involved and identify the type of reaction.

5. You are provided with two containers made up of copper and aluminium. You are also provided with solutions of dilute HCl , dilute $\mathrm{HNO}_{3}, \mathrm{ZnCl}_{2}$ and $\mathrm{H}_{2} \mathrm{O}$. In which of the above containers these solutions can be kept?

\section*{Multiple Choice Questions}

DIRECTIONS : This section contains multiple choice questions. Each question has four choices (a), (b), (c) and (d) out of which ONLY ONE is correct.

1. Which of the following reactions involves the combination of two elements?
(a) $\mathrm{CaO}+\mathrm{CO}_{2} \rightarrow \mathrm{CaCO}_{3}$
(b) $4 \mathrm{Na}+\mathrm{O}_{2} \rightarrow 2 \mathrm{Na}_{2} \mathrm{O}$
(c) $\mathrm{SO}_{2}+\frac{1}{2} \mathrm{O}_{2} \rightarrow \mathrm{SO}_{3}$
(d) $\mathrm{NH}_{3}+\mathrm{HCl} \rightarrow \mathrm{NH}_{4} \mathrm{Cl}$

2. When hydrogen sulphide gas is passed through a blue solution of copper sulphate, a black precipitate of copper sulphide is obtained and the sulphuric acid so formed remains in the solution. The reaction is an example of -
(a) a combination reaction
(b) a displacement reaction
(c) a decomposition reaction
(d) a double decomposition reaction

3. What happens when copper rod is dipped in iron sulphate solution?
(a) Copper displaces iron
(b) Blue colour of copper sulphate solution is obtained
(c) No reaction takes place
(d) Reaction is exothermic

4. A student added dilute HCl to a test tube containing zinc granules and made following observations which one is correct?
(a) The zinc surface became dull and black.
(b) A gas evolved which burns with a pop sound.
(c) The solution remained colourless.
(d) The solution becomes green in colour.

5. A dilute solution of sodium carbonate was added to two test tubes (A) containing dil HCl and (B) containing dilute NaOH . The correct observation was -
(a) a brown coloured gas liberated in test tube A.
(b) a brown coloured gas liberated in test tube B.
(c) a colourless gas liberated in test tube A.
(d) a colourless gas liberated in test tube B.

6. A balanced chemical equation is in accordance with -
(a) Avogadro's law
(b) law of multiple proportion
(c) law of conservation of mass
(d) law of gaseous volumes.

7. The equation
$$\mathrm{Cu}+x \mathrm{HNO}_{3} \rightarrow \mathrm{Cu}\left(\mathrm{NO}_{3}\right)_{2}+y \mathrm{NO}_{2}+2 \mathrm{H}_{2} \mathrm{O}$$
The values of $x$ and $y$ are -
(a) 3 and 5
(b) 8 and 6
(c) 4 and 2
(d) 7 and 1

8. $\mathrm{Zn}+\mathrm{H}_{2} \mathrm{SO}_{4}($ dil $) \longrightarrow \mathrm{ZnSO}_{4}+\mathrm{H}_{2} \uparrow$ Above reaction is -
(a) decomposition reaction
(b) single displacement reaction
(c) combination reaction
(d) synthesis reaction

9. The reaction in which two compounds exchange their ions to form two new compounds is -
(a) a displacement reaction
(b) a decomposition reaction
(c) an isomerization reaction
(d) a double displacement reaction

10. When the gases sulphur dioxide and hydrogen sulphide mix in the presence of water, the reaction is $\mathrm{SO}_{2}+2 \mathrm{H}_{2} \mathrm{~S} \rightarrow 2 \mathrm{H}_{2} \mathrm{O}+3 \mathrm{~S}$. Here hydrogen sulphide is acting as -
(a) an oxidising agent
(b) a reducing agent
(c) a dehydrating agent
(d) a catalyst

11. $\mathrm{CuO}+\mathrm{H}_{2} \rightarrow \mathrm{H}_{2} \mathrm{O}+\mathrm{Cu}$, reaction is an example of -
(a) redox reaction
(b) synthesis reaction
(c) neutralisation
(d) analysis reaction

12. A substance which oxidises itself and reduces other is known as -
(a) oxidising agent
(b) reducing agent
(c) both of these
(d) none of these

13. A redox reaction is one in which -
(a) both the substances are reduced.
(b) both the substances are oxidised.
(c) an acid is neutralised by the base.
(d) one substance is oxidised while the other is reduced.

14. In the following equations:
$\mathrm{Na}_{2} \mathrm{CO}_{3}+x \mathrm{HCl} \rightarrow 2 \mathrm{NaCl}+\mathrm{CO}_{2}+\mathrm{H}_{2} \mathrm{O}$, the value of $x$ is-
(a) 1
(b) 2
(c) 3
(d) 4

15. In the equation, $\mathrm{NaOH}+\mathrm{HNO}_{3} \rightarrow \mathrm{NaNO}_{3}+\mathrm{H}_{2} \mathrm{O}$ nitric acid is acting as -
(a) an oxidising agent
(b) an acid
(c) a nitrating agent
(d) a dehydrating agent

16. $\mathrm{Fe}_{2} \mathrm{O}_{3}+2 \mathrm{Al} \rightarrow \mathrm{Al}_{2} \mathrm{O}_{3}+2 \mathrm{Fe}$
The above reaction is an example of $\mathrm{a}-$
(a) combination reaction
(b) double displacement reaction
(c) decomposition reaction
(d) displacement reaction

17. White silver chloride in sunlight turns to -
(a) grey
(b) yellow
(c) remain white
(d) red

18. Black and white photography uses -
(a) decomposition of silver chloride.
(b) decomposition of silver bromide.
(c) both
(d) none of these

19. When copper powder is heated it gets coated with -
(a) black copper oxide
(b) yellow copper oxide
(c) red copper oxide
(d) None of these

20. Combination of phosphorus and oxygen is an example of-
(a) oxidation
(b) reduction
(c) rancidity
(d) None of these

21. Rusting of iron is an example of -
(a) reduction
(b) redox
(c) oxidation
(d) dissociation

22. Which of the following does not corrode when exposed to the atmosphere?
(a) Iron
(b) Copper
(c) Gold
(d) Silver

23. Take about $1.0 \mathrm{~g} \mathrm{CaCO}_{3}$ in a test tube. Heat it over a flame, a colourless gas comes out. The reaction is called a
(a) decomposition reaction
(b) displacement reaction
(c) double decomposition reaction
(d) double displacement reaction

24. Hydrogen sulphide $\left(\mathrm{H}_{2} \mathrm{~S}\right)$ is a strong reducing agent. Which of the following reactions shows its reducing action?
(a) $\mathrm{Cd}\left(\mathrm{NO}_{3}\right)_{2}+\mathrm{H}_{2} \mathrm{~S} \longrightarrow \mathrm{CdS}+2 \mathrm{HNO}_{3}$
(b) $\mathrm{CuSO}_{4}+\mathrm{H}_{2} \mathrm{~S} \longrightarrow \mathrm{CuS}+\mathrm{H}_{2} \mathrm{SO}_{4}$
(c) $2 \mathrm{FeCl}_{3}+\mathrm{H}_{2} \mathrm{~S} \longrightarrow 2 \mathrm{FeCl}_{2}+2 \mathrm{HCl}+\mathrm{S}$
(d) $\mathrm{Pb}\left(\mathrm{NO}_{3}\right)_{2}+\mathrm{H}_{2} \mathrm{~S} \longrightarrow \mathrm{PbS}+2 \mathrm{CH}_{3} \mathrm{COOH}$

25. $2 \mathrm{CuI} \rightarrow \mathrm{Cu}+\mathrm{CuI}_{2}$, the reaction is -
(a) redox
(b) neutralisation
(c) oxidation
(d) reduction

26. When copper turnings are added to silver nitrate solution, a blue coloured solution is formed after some time. It is because, copper -
(a) displaces silver from the solution
(b) forms a blue coloured complex with $\mathrm{AgNO}_{3}$
(c) is oxidised to $\mathrm{Cu}^{2+}$
(d) is reduced to $\mathrm{Cu}^{2+}$

27. $\mathrm{Zn}^{2+}(\mathrm{aq})+2 \mathrm{e}^{-} \rightarrow \mathrm{Zn}(\mathrm{s})$. This is -
(a) oxidation
(b) reduction
(c) redox reaction
(d) none of these

28. A substance A reacts with another substance B to produce the product C and a gas D . If a mixture of the gas D and ammonia is passed through an aqueous solution of C , baking soda is formed. The substances A and B are
[NTSE]
(a) HCl and NaOH
(b) HCl and $\mathrm{Na}_{2} \mathrm{CO}_{3}$
(c) Na and HCl
(d) $\mathrm{Na}_{2} \mathrm{CO}_{3}$ and $\mathrm{H}_{2} \mathrm{O}$

29. Chemically the 'water gas' is
[JSTSE]
(a) $\mathrm{H}_{2} \mathrm{O}$ (gaseous)
(b) $\mathrm{CO}_{2}+\mathrm{H}_{2}$
(c) $\mathrm{CH}_{4}+\mathrm{H}_{2} \mathrm{O}$
(d) $\mathrm{CO}+\mathrm{H}_{2}$

30. The oxidation number of sulphur is -4 in
[KVPY]
(a) $\mathrm{H}_{2} \mathrm{~S}$
(b) $\mathrm{CS}_{2}$
(c) $\mathrm{Na}_{2} \mathrm{SO}_{4}$
(d) $\mathrm{Na}_{2} \mathrm{SO}_{3}$

31. Identify the endothermic process from the following
[JSTSE]
(a) Addition of conc. HCl to water
(b) $\mathrm{CH}_{4}(\mathrm{~g})+2 \mathrm{O}_{2}(\mathrm{~g}) \longrightarrow \mathrm{CO}_{2}(\mathrm{~g})+2 \mathrm{H}_{2} \mathrm{O}(\mathrm{l})$
(c) $\mathrm{H}_{2} \mathrm{O}(\mathrm{l}) \longrightarrow \mathrm{H}_{2} \mathrm{O}(\mathrm{g})$
(d) $\mathrm{CaO}(\mathrm{s})+\mathrm{H}_{2} \mathrm{O}(\mathrm{l}) \longrightarrow \mathrm{Ca}(\mathrm{OH})_{2}(\mathrm{aq})$

32. The schematic diagram is given below
[NTSE]
Which of the following is a correct statement?
(a) A and E are chemically same.
(b) A and D are chemically same.
(c) D and E are chemically same.
(d) C and E are chemically same.

33. The oxidation states of P atom in $\mathrm{POCl}_{3}, \mathrm{H}_{2} \mathrm{PO}_{3}$ and $\mathrm{H}_{2} \mathrm{P}_{2} \mathrm{O}_{6}$, respectively are
[KVPY]
(a) $+5,+4,+4$
(b) $\quad+5,+5,+4$
(c) $+4,+4,+5$
(d) $+3,+4,+5$

34. The process of respiration is :
[JSTSE]
(a) Oxidation reaction which is endothermic
(b) Reduction reaction which is endothermic
(c) Combination reaction which is exothermic
(d) Oxidation reaction which is exothermic

35. Silver articles become black when exposed to air. It is due to the formation of
[JSTSE]
(a) Silver oxide
(b) Silver nitrate
(c) Silver chloride
(d) Silve sulphide

36. A test tube along with calcium carbonate in it initially weighed 30.08 g . A heating experiment was performed on this test tube till calcium carbonate completely decomposed with evolution of a gas. Loss of weight during this experiment was 4.40 g . What is the weight of the empty test tube in this experiment?
(a) 20.08 g
(b) 21.00 g
(c) 24.50 g
(d) 2.008 g

37. Match chemical reactions given in the List I with the type of chemical reactions given in List II and select the correct answer using the options given below:
[NTSE]

\section*{Passage Based Questions}

DIRECTIONS : Study the given paragraph(s) and answer the following questions.

\section*{Passage}

An element placed above in the activity series will replace the element placed below it from its aqueous solution. Reactivity of metals towards other elements decreases as you go down the series. The stability of their compounds also decreases.
Any metal above hydrogen reacts with acids, replaces hydrogen from acids.
The more active a metal, the more strongly it holds on to oxygen in an oxide and therefore, the more strongly the oxide resists decomposition into its elements upon heating.
1. Copper displaces which of the following metals from its salt solution?
(a) Zinc
(b) Iron
(c) Silver
(d) Nickel
2. Which of the following oxides can be decomposed with difficulty?
(a) CuO
(b) ZnO
(c) AgO
(d) CrO
3. Which of the following statement is correct?
(a) Elements near the top of the series are never found free in nature.
(b) Elements near the bottom of the series are often found free in nature.
(c) Elements near the top of the series are found free in nature.
(d) both (a) and (b)

\section*{Assertion \& Reason}

DIRECTIONS : Each of these questions contains an Assertion followed by reason. Read them carefully and answer the question on the basis of following options. You have to select the one that best describes the two statements.

(a) If both Assertion and Reason are correct and Reason is the correct explanation of Assertion.

(b) If both Assertion and Reason are correct, but Reason is not the correct explanation of Assertion.

(c) If Assertion is correct but Reason is incorrect.

(d) If Assertion is incorrect but Reason is correct.

1. Assertion : Stannous chloride gives grey precipitate with mercuric chloride, but stannic chloride does not do so.
Reason : Stannous chloride is a powerful oxidising agent which oxidises mercuric chloride to mercury.

2. Assertion : Corrosion of iron is commonly known as rusting.
Reason : Corrosion of iron occurs in presence of water and air.

3. Assertion : In a reaction
$\mathrm{Zn}(\mathrm{s})+\mathrm{CuSO}_{4}(\mathrm{aq}) \longrightarrow \mathrm{ZnSO}_{4}(\mathrm{aq})+\mathrm{Cu}(\mathrm{s})$,
Zn is a reductant but itself get oxidized.
Reason : In a redox reaction, oxidant is reduced by accepting electrons and reductant is oxidized by losing electrons.

Column I

(A) $\mathrm{KClO}_{3} \xrightarrow{\Delta}$

(B) $\mathrm{ZnCO}_{3} \xrightarrow{\Delta}$

(C) $\mathrm{H}_{2} \mathrm{CO}_{3} \xrightarrow{\Delta}$

(D) $\mathrm{C}_{2} \mathrm{H}_{6} \xrightarrow{\Delta}$

(a) & p & s,r & q,r & q,r |

(b) & p & q,r & s,r & r,p |

(c) & q,r & s,p & p,s & r |

(d) & r & q & s & p

\section*{Column II}

(p) $\mathrm{O}_{2}$

(q) $\mathrm{H}_{2} \mathrm{O}$

(r) $\quad \mathrm{CO}_{2}$

(s) ZnO

(s) ZnO

\section*{Multiple Matching Questions}

DIRECTIONS : Following question has Column I and Column II. Any given option in Column I can have correct matching with one or more option given in Column II. Match the entries in column I with entries in column II.

1.

\section*{Integer/Numerical Value Type Questions}

DIRECTIONS (Qs. 1-4) : Following are integer/numerical value based questions. Each question, when worked out will result in an integer/numerical value.

1. The following equation is unbalanced, on balancing the equation what will be the value of $x$ ?
$\mathrm{Na}_{2} \mathrm{CO}_{3}+x \mathrm{HCl} \longrightarrow 2 \mathrm{NaCl}+\mathrm{CO}_{2}+\mathrm{H}_{2} \mathrm{O}$

2. In the reaction $\mathrm{N}_{2} \mathrm{O}_{5} \longrightarrow \mathrm{NO}_{2}+\mathrm{O}_{2}$,
how many moles of $\mathrm{NO}_{2}$ is produced when 2 moles of $\mathrm{N}_{2} \mathrm{O}_{5}$ are dissociated?

3. (A) $\mathrm{Fe}+\mathrm{S} \longrightarrow \mathrm{FeS}$
(B) $\mathrm{CaO}+\mathrm{CO}_{2} \longrightarrow \mathrm{CaCO}_{3}$
(C) $\mathrm{Ca}(\mathrm{OH})_{2} \xrightarrow{\text { Heat }} \mathrm{CaO}+\mathrm{H}_{2} \mathrm{O}$
(D) $\mathrm{CuO}+\mathrm{H}_{2} \xrightarrow{\text { Heat }} \mathrm{Cu}+\mathrm{H}_{2} \mathrm{O}$
Out of the four reactions given above, the number of combination reactions is/are

4. (A) $\mathrm{N}_{2}+3 \mathrm{H}_{2} \longrightarrow 2 \mathrm{NH}_{3}+22.4 \mathrm{kcal}$
(B) $\mathrm{N}_{2}+\mathrm{O}_{2}+43.2 \mathrm{kcal} \longrightarrow 2 \mathrm{NO}$
(C) $\mathrm{C}+2 \mathrm{H}_{2} \longrightarrow \mathrm{CH}_{4}+74.8 \mathrm{~kJ}$
How many reactions from the given reaction are endothermic reactions?

\section*{Multiple Choice Questions}

DIRECTIONS (Qs. 1-23) : This section contains multiple choice questions. Each question has four choices (a), (b), (c) and (d) out of which ONLY ONE is correct.

1. The loss of electron is termed as-
(a) oxidation
(b) reduction
(c) combustion
(d) neutralization

2. Reduction involves-
(a) loss of electrons
(b) gain of electrons
(c) increase in the valency of positive part
(d) decrease in the valency of negative part

3. $\quad \mathrm{Zn}^{2+}$ (aq.) $+2 \mathrm{e}^{-} \longrightarrow \mathrm{Zn}$ (s). This is-
(a) Oxidation
(b) Reduction
(c) Redox reaction
(d) None of the above

4. The oxidation number of sulphur in $\mathrm{S}_{8}, \mathrm{~S}_{2} \mathrm{~F}_{2}, \mathrm{H}_{2} \mathrm{~S}$ respectively, are-
(a) 0, +1 and -2
(b) +2, +1 and -2
(c) 0, +1 and +2
(d) $-2,+1$ and -2

5. Oxidation number of carbon in $\mathrm{CH}_{2} \mathrm{Cl}_{2}$ is-
(a) -4
(b) +4
(c) 0
(d) -2

6. The oxidation state of osmium (Os) in $\mathrm{OsO}_{4}$ is-
(a) +7
(b) +6
(c) +4
(d) +8

7. Which of the following transition metal has zero oxidation state ?
(a) $\left[\mathrm{Fe}(\mathrm{CO})_{5}\right]$
(b) $\mathrm{NH}_{2} \cdot \mathrm{NH}_{2}$
(c) $\mathrm{NOClO}_{4}$
(d) $\mathrm{CrO}_{5}$

8. Oxidation number of S in $\mathrm{S}^{2-}$ is-
(a) -2
(b) 0
(c) -6
(d) +6

9. The oxidation number of Mn in $\mathrm{KMnO}_{4}$ is-
(a) +7
(b) -7
(c) +1
(d) -1

10. Oxidation number of oxygen atom in $\mathrm{O}_{2}$ molecule is-
(a) 0
(b) -2
(c) +2
(d) $-\frac{1}{2}$

11. The oxidation number of N in $\mathrm{NH}_{3}$ is-
(a) +3
(b) +5
(c) -3
(d) 0

12. Oxygen has an oxidation state of +2 in the compound-
(a) $\mathrm{H}_{2} \mathrm{O}_{2}$
(b) $\mathrm{CO}_{2}$
(c) $\mathrm{H}_{2} \mathrm{O}$
(d) $\mathrm{F}_{2} \mathrm{O}$

13. In which of the following reactions, $\mathrm{H}_{2} \mathrm{O}_{2}$ acts as a reducing agent?
(a) $2 \mathrm{KI}+\mathrm{H}_{2} \mathrm{O}_{2} \longrightarrow 2 \mathrm{KOH}+\mathrm{I}_{2}$
(b) $2 \mathrm{FeSO}_{4}+\mathrm{H}_{2} \mathrm{SO}_{4}+\mathrm{H}_{2} \mathrm{O}_{2} \longrightarrow \mathrm{Fe}_{2}\left(\mathrm{SO}_{4}\right)_{3}+2 \mathrm{H}_{2} \mathrm{O}$
(c) $\mathrm{PbS}+4 \mathrm{H}_{2} \mathrm{O}_{2} \longrightarrow \mathrm{PbSO}_{4}+4 \mathrm{H}_{2} \mathrm{O}$
(d) $\mathrm{Ag}_{2} \mathrm{O}+\mathrm{H}_{2} \mathrm{O}_{2} \longrightarrow 2 \mathrm{Ag}+\mathrm{H}_{2} \mathrm{O}+\mathrm{O}_{2}$

14. In a balance equation $\mathrm{H}_{2} \mathrm{SO}_{4}+x \mathrm{HI} \rightarrow \mathrm{H}_{2} \mathrm{~S}+y \mathrm{I}_{2}+z \mathrm{H}_{2} \mathrm{O}$, the values of $x, y, z$ are-
(a) $x=3, y=5, z=2$
(b) $x=4, y=8, z=5$
(c) $x=8, y=4, z=4$
(d) $x=5, y=3, z=4$

15. Consider the following reaction :
$x \mathrm{C}_{2} \mathrm{H}_{6}(\mathrm{~g})+y \mathrm{O}_{2}(\mathrm{~g}) \longrightarrow m \mathrm{CO}_{2}(\mathrm{~g})+n \mathrm{H}_{2} \mathrm{O}(\mathrm{l})$
Which of the following set of coefficients balances the above redox reaction?
{lllll}
& $x$ & $y$ & $m$ & $n$ |
(a) & 1 & 3 & 2 & 2 |
(b) & 2 & 7 & 4 & 6 |
(c) & 2 & 3 & 2 & 2 |
(d) & 1 & 7 & 2 & 3

16. What will be the value of $x, y$ and $z$ in following equation?
$\mathrm{H}_{2} \mathrm{C}_{2} \mathrm{O}_{4}+x \mathrm{H}_{2} \mathrm{O}_{2} \rightarrow y \mathrm{CO}_{2}+z \mathrm{H}_{2} \mathrm{O}$
(a) $x=1, y=2, z=2$
(b) $x=2, y=2, z=2$
(c) $x=2, y=2, z=1$
(d) $x=1, y=2, z=4$

17. Which of the following reactions is an example of a redox reaction?
[NTSE]
(a) $\mathrm{XeF}_{4}+\mathrm{O}_{2} \mathrm{~F}_{2} \longrightarrow \mathrm{XeF}_{6}+\mathrm{O}_{2}$
(b) $\mathrm{XeF}_{2}+\mathrm{PF}_{5} \longrightarrow\left[\mathrm{XeF}^{+} \mathrm{PF}_{6}^{-}\right.$
(c) $\mathrm{XeF}_{6}+\mathrm{H}_{2} \mathrm{O} \longrightarrow \mathrm{XeOF}_{4}+2 \mathrm{HF}$
(d) $\mathrm{XeF}_{6}+2 \mathrm{H}_{2} \mathrm{O} \longrightarrow \mathrm{XeO}_{2} \mathrm{~F}_{2}+4 \mathrm{HF}$

18. The formal oxidation numbers of Cr and Cl in the ions $\mathrm{Cr}_{2} \mathrm{O}_{7}^{2-}$ and $\mathrm{ClO}_{3}{ }^{-}$, respectively are
[KVPY 2018]
(a) +6 and +7
(b) +7 and +5
(c) +6 and +5
(d) +8 and +7

19. The oxidation states of Cr in $\left[\mathrm{Cr}\left(\mathrm{H}_{2} \mathrm{O}\right)_{6}\right] \mathrm{Cl}_{3},\left[\mathrm{Cr}\left(\mathrm{C}_{6} \mathrm{H}_{6}\right)_{2}\right]$, and $\mathrm{K}_{2}\left[\mathrm{Cr}(\mathrm{CN})_{2}(\mathrm{O})_{2}(\mathrm{O})_{2}\left(\mathrm{NH}_{3}\right)\right]$ respectively are
[NTSE]
(a) $+3,+4$, and +6
(b) +3, +2, and +4
(c) $\quad+3,0$, and +6
(d) $+3,0$, and +4

20. The correct order of N-compounds in its decreasing order of oxidation states is
[JSTSE]
(a) $\mathrm{HNO}_{3}, \mathrm{NO}, \mathrm{N}_{2}, \mathrm{NH}_{4} \mathrm{Cl}$
(b) $\mathrm{HNO}_{3}, \mathrm{NO}, \mathrm{NH}_{4} \mathrm{Cl}, \mathrm{N}_{2}$
(c) $\mathrm{NH}_{4} \mathrm{Cl}, \mathrm{N}_{2}, \mathrm{NO}, \mathrm{HNO}_{3}$
(d) $\mathrm{HNO}_{3}, \mathrm{NH}_{4} \mathrm{Cl}, \mathrm{NO}, \mathrm{N}_{2}$

21. For the redox reaction
$\mathrm{MnO}_{4}^{-}+\mathrm{C}_{2} \mathrm{O}_{4}^{2-}+\mathrm{H}^{+} \longrightarrow \mathrm{Mn}^{2+}+\mathrm{CO}_{2}+\mathrm{H}_{2} \mathrm{O}$
The correct coefficients of the reactants for the balanced equation are
[JSTSE]
{llll}
& $\mathrm{MnO}_{4}^{-}$ & $\mathrm{C}_{2} \mathrm{O}_{4}^{2-}$ & $\mathrm{H}^{+}$ |
(a) & 16 & 5 & 2 |
(b) & 2 & 5 & 16 |
(c) & 5 & 16 & 2 |
(d) & 2 & 16 & 5

22. The correct order of the oxidation states of nitrogen in NO , $\mathrm{N}_{2} \mathrm{O}, \mathrm{NO}_{2}$ and $\mathrm{N}_{2} \mathrm{O}_{3}$ is:
[NTSE]
(a) $\mathrm{NO}_{2}<\mathrm{NO}<\mathrm{N}_{2} \mathrm{O}_{3}<\mathrm{N}_{2} \mathrm{O}$
(b) $\mathrm{NO}_{2}<\mathrm{N}_{2} \mathrm{O}_{3}<\mathrm{NO}<\mathrm{N}_{2} \mathrm{O}$
(c) $\mathrm{N}_{2} \mathrm{O}<\mathrm{N}_{2} \mathrm{O}_{3}<\mathrm{NO}<\mathrm{NO}_{2}$
(d) $\mathrm{N}_{2} \mathrm{O}<\mathrm{NO}<\mathrm{N}_{2} \mathrm{O}_{3}<\mathrm{NO}_{2}$

23. What is the change in oxidation number of carbon in the following reaction?
[JSTSE]
$\mathrm{CH}_{4}(g)+4 \mathrm{Cl}_{2}(g) \longrightarrow \mathrm{CCl}_{4}(l)+4 \mathrm{HCl}(g)$
(a) 0 to +4
(b) -4 to +4
(c) 0 to - 4
(d) +4 to +4

\section*{Assertion \& Reason}

DIRECTIONS (Qs. 30-32) : Each of these questions contains an assertion followed by reason. Read them carefully and answer the question on the basis of following options. You have to select the one that best describes the two statements.

(a) If both Assertion and Reason are correct and Reason is the correct explanation of Assertion.

(b) If both Assertion and Reason are correct, but Reason is not the correct explanation of Assertion.

(c) If Assertion is correct but Reason is incorrect.

(d) If Assertion is incorrect but Reason is correct.

30. Assertion : In a reaction
$\mathrm{Zn}(\mathrm{s})+\mathrm{CuSO}_{4}(\mathrm{aq}) \longrightarrow \mathrm{ZnSO}_{4}(\mathrm{aq})+\mathrm{Cu}(\mathrm{s})$
Zn is a reductant but itself gets oxidized.
Reason : In a redox reaction, oxidant is reduced by accepting electrons and reductant is oxidized by losing electrons.

31. Assertion : $\mathrm{Mg}(\mathrm{s})+\mathrm{F}_{2}(\mathrm{~s}) \rightarrow \mathrm{MgF}_{2}(\mathrm{~s})$, magnesium loses electrons and acts as a reducing agent.
Reason : Reduction in general means acceptance of electron(s) by a reactant.

32. Assertion : In a redox reaction, the oxidation number of the oxidant decreases, while that of reductant increases.
Reason : Oxidant gains electron (s) reductant loses electrons (s).

\section*{Matching Questions}

DIRECTIONS (Qs. 33-34) : Each question contains two columns. ( $A, B, C, D$ ) in column I have to be matched with ( $p$, $q, r, s$ ) in column II.

33.
{|l|l|l|l|l|}

Column I & Column II |

(B) & $\mathrm{Mg} \longrightarrow \mathrm{Mg}^{2+}+2 \mathrm{e}^{-}$ & & (q) & displacement reaction |

(C) & $\mathrm{Sn}^{4+}+2 \mathrm{e}^{-} \longrightarrow \mathrm{Sn}^{2+}$ & & (r) & Redox reaction |

(D) & $\mathrm{C}+\mathrm{O}_{2} \longrightarrow \mathrm{CO}_{2}$ & & (s) & Oxidation reaction |

(a) & r,q & s & & |

(b) & r,q & s & & |

(c) & s & r,q & & |

(d) & s,q & p,s & & |

34.

\section*{Passage Based Questions}

DIRECTIONS (Qs. 35-37) : Study the given paragraph(s) and answer the following questions.

\section*{Passage}

Oxidation number is defined as the charge which an atom of the element has in its ion or appears to have when present in the combined state with other atoms.
There are certain rules for assigning oxidation number. Some of these rules are given below.
- The oxidation number of all the atoms of different elements in their respective elementary states and allotropic forms is taken to be zero.
- The O.N. of a monoatomic ion is the same as the charge on it.
- The O.N. of hydrogen is +1 when combined with nonmetals and is -1 when combined with active metals called metal hydrides
- The O.N. of alkali metals (Li, Na, K, etc.) is always + 1 and that of alkaline earth metals ( $\mathrm{Be}, \mathrm{Mg}, \mathrm{Ca}$, etc.) is +2 .
- The algebraic sum of the O.N. of all the atoms in a compound must be zero. In polyatomic ion, the algebraic
sum of all the O.N.'s of atoms of the ion must equal the charge on the ion.
35. What is the oxidation number of P in $\mathrm{PO}_{4}^{3-}$ and S in $\mathrm{SO}_{4}^{2-}$ ?
(a) $\mathrm{P}=+5, \mathrm{~S}=+3$
(b) $\mathrm{P}=+3 . \mathrm{S}=+5$
(c) $\mathrm{P}=+5, \mathrm{~S}=+6$
(d) $\mathrm{P}=+6, \mathrm{~S}=+6$
36. Oxygen has an oxidation state of +2 in the compound :
(a) $\mathrm{H}_{2} \mathrm{O}_{2}$
(b) $\mathrm{CO}_{2}$
(c) $\mathrm{H}_{2} \mathrm{O}$
(d) $\mathrm{F}_{2} \mathrm{O}$
37. What is the correct increasing order of oxidation state of nitrogen in following compounds?
$\mathrm{NH}_{3}, \mathrm{~N}_{2}, \mathrm{NH}_{2} \mathrm{OH}, \mathrm{NO}_{2}$
(a) $\mathrm{NH}_{3}<\mathrm{NO}_{2}<\mathrm{N}_{2}<\mathrm{NH}_{2} \mathrm{OH}$
(b) $\mathrm{NO}_{2}<\mathrm{NH}_{3}<\mathrm{NH}_{2} \mathrm{OH}<\mathrm{NH}_{3}$
(c) $\mathrm{NH}_{3}<\mathrm{NH}_{2} \mathrm{OH}<\mathrm{NO}_{2}<\mathrm{N}_{2}$
(d) $\mathrm{NH}_{3}<\mathrm{NH}_{2} \mathrm{OH}<\mathrm{N}_{2}<\mathrm{NO}_{2}$

\section*{Integer Type Questions}

DIRECTIONS (Qs. 38-42) : Following are integer based questions. Each question, when worked out will result in one integer from 0 to 9 (both inclusive).

38. Among $\mathrm{NH}_{3}, \mathrm{HNO}_{3}$ and $\mathrm{Mg}_{3} \mathrm{~N}_{2}$ how many molecules have nitrogen in negative oxidation state?

39. When $\mathrm{K}_{2} \mathrm{Cr}_{2} \mathrm{O}_{7}$ is converted into $\mathrm{K}_{2} \mathrm{CrO}_{4}$, then what is the change in oxidation number of chromium?

40. Consider the following reaction
$\mathrm{PbS}+n \mathrm{H}_{2} \mathrm{O}_{2} \longrightarrow \mathrm{PbSO}_{4}+4 \mathrm{H}_{2} \mathrm{O}$
What is the value of coefficient ' $n$ ' in the above equation?

41. Find the oxidation number of S in $\left(\mathrm{CH}_{3}\right)_{2} \mathrm{SO}$.

42. Find the difference in oxidation states of nitrogen in nitrous acid and nitric acid.
