% Bypass questions from: ch12_c8_some_natural_phenomena_QA.mmd
% Subject: Physics | count: 13

% --- Q3a ---
Like charges attract each other.

% --- Q3b ---
A charged glass rod attracts a charged plastic straw.

% --- Q3c ---
Lightning conductor cannot protect a building from lightning.

% --- Q3d ---
Earthquakes can be predicted in advance.

% --- Q4 ---
Sometimes, a crackling sound is heard while taking off a sweater during winters. Explain.

% --- Q5 ---
Explain why a charged body loses its charge if we touch it with our hand.

% --- Q6 ---
Name the scale on which the destructive energy of an earthquake is measured. An earthquake measures 3 on this scale. Would it be recorded by a seismograph? Is it likely to cause much damage?

% --- Q7 ---
Suggest three measures to protect ourselves from lightning.

% --- Q8 ---
Explain why a charged balloon is repelled by another charged balloon whereas an uncharged balloon is attracted by another charged balloon?

% --- Q9 ---
Describe with the help of a diagram an instrument which can be used to detect a charged body.

% --- Q10 ---
List three states in India where earthquakes are more likely to strike.

% --- Q11 ---
Suppose you are outside your home and an earthquake strikes. What precaution would you take to protect yourself?

% --- Q12 ---
The weather department has predicted that a thunderstorm is likely to occur on a certain day. Suppose you have to go out on that day. Would you carry an umbrella? Explain.
